version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - pg:/var/lib/postgresql/data
      - .:/app

  redis:
    image: redis

  app:
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        - USER
        - UID

    command: sh -c "rm -f tmp/pids/server.pid && /app/bin/rails s -b 0.0.0.0"
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /var/tmp:/var/tmp:cached
      - /tmp:/tmp:cached
      - ./tmp:/app/tmp
    depends_on:
      - db
      - redis

volumes:
    pg:
