default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>  
  host: <%= ENV.fetch('PG_HOST') { 'db' } %>
  username: <%= ENV.fetch('PG_USER') { 'postgres' } %>
  password: <%= ENV.fetch('PG_PASSWORD') { '' } %>

development:
  <<: *default
  database: controllers_workshop_dev

test:
  <<: *default
  database: controllers_workshop_test

production:
  <<: *default
  database: controllers_workshop_prod
